# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_calc_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("""
            QWidget {
                background-color: #151b38;
                color: #ffffff;
                border-color: #051a39;
            }
            
            QTextEdit {
                background-color: #ffffff;
                color: #010201;
                border-color: #051a39;
                border-radius: 3px;
            }
            
            QPushButton {
                background-color: #607cff;
                color: #ffffff;
                border-style: solid;
                border-width: 1px;
                border-radius: 3px;
                border-color: #051a39;
                padding: 5px;
            }
            
            QPushButton::hover {
                background-color: #8399ff;
                color: #ffffff;
                border-style: solid;
                border-width: 1px;
                border-radius: 3px;
                border-color: #051a39;
                padding: 5px;
            }
            
            
            QPushButton::pressed {
                background-color: #4969ff;
                color: #ffffff;
                border-style: solid;
                border-width: 1px;
                border-radius: 3px;
                border-color: #051a39;
                padding: 5px;
            }
""")
        
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnC = QtWidgets.QPushButton(self.centralwidget)
        self.btnC.setGeometry(QtCore.QRect(50, 140, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnC.setFont(font)
        self.btnC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnC.setMouseTracking(False)
        self.btnC.setObjectName("btnC")
        self.btnCE = QtWidgets.QPushButton(self.centralwidget)
        self.btnCE.setGeometry(QtCore.QRect(120, 140, 60, 60))
        self.btnCE.setFont(font)
        self.btnCE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCE.setMouseTracking(False)
        self.btnCE.setObjectName("btnCE")
        self.btnAns = QtWidgets.QPushButton(self.centralwidget)
        self.btnAns.setGeometry(QtCore.QRect(189, 140, 61, 60))
        self.btnAns.setFont(font)
        self.btnAns.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAns.setMouseTracking(False)
        self.btnAns.setObjectName("btnAns")
        self.btnNine = QtWidgets.QPushButton(self.centralwidget)
        self.btnNine.setGeometry(QtCore.QRect(190, 210, 60, 60))
        self.btnNine.setFont(font)
        self.btnNine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNine.setMouseTracking(False)
        self.btnNine.setObjectName("btnNine")
        self.btnSeven = QtWidgets.QPushButton(self.centralwidget)
        self.btnSeven.setGeometry(QtCore.QRect(50, 210, 60, 60))
        self.btnSeven.setFont(font)
        self.btnSeven.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSeven.setMouseTracking(False)
        self.btnSeven.setObjectName("btnSeven")
        self.btnEight = QtWidgets.QPushButton(self.centralwidget)
        self.btnEight.setGeometry(QtCore.QRect(120, 210, 60, 60))
        self.btnEight.setFont(font)
        self.btnEight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEight.setMouseTracking(False)
        self.btnEight.setObjectName("btnEight")
        self.btnMul = QtWidgets.QPushButton(self.centralwidget)
        self.btnMul.setGeometry(QtCore.QRect(260, 140, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnMul.setFont(font)
        self.btnMul.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMul.setMouseTracking(False)
        self.btnMul.setObjectName("btnMul")
        self.btnSix = QtWidgets.QPushButton(self.centralwidget)
        self.btnSix.setGeometry(QtCore.QRect(190, 280, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSix.setFont(font)
        self.btnSix.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSix.setMouseTracking(False)
        self.btnSix.setObjectName("btnSix")
        self.btnFour = QtWidgets.QPushButton(self.centralwidget)
        self.btnFour.setGeometry(QtCore.QRect(50, 280, 60, 60))
        self.btnFour.setFont(font)
        self.btnFour.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFour.setMouseTracking(False)
        self.btnFour.setObjectName("btnFour")
        self.btnFive = QtWidgets.QPushButton(self.centralwidget)
        self.btnFive.setGeometry(QtCore.QRect(120, 280, 60, 60))
        self.btnFive.setFont(font)
        self.btnFive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFive.setMouseTracking(False)
        self.btnFive.setObjectName("btnFive")
        self.btnDiv = QtWidgets.QPushButton(self.centralwidget)
        self.btnDiv.setGeometry(QtCore.QRect(260, 210, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnDiv.setFont(font)
        self.btnDiv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDiv.setMouseTracking(False)
        self.btnDiv.setObjectName("btnDiv")
        self.btnThree = QtWidgets.QPushButton(self.centralwidget)
        self.btnThree.setGeometry(QtCore.QRect(190, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnThree.setFont(font)
        self.btnThree.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnThree.setMouseTracking(False)
        self.btnThree.setObjectName("btnThree")
        self.btnOne = QtWidgets.QPushButton(self.centralwidget)
        self.btnOne.setGeometry(QtCore.QRect(50, 350, 60, 60))
        self.btnOne.setFont(font)
        self.btnOne.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOne.setMouseTracking(False)
        self.btnOne.setObjectName("btnOne")
        self.btnTwo = QtWidgets.QPushButton(self.centralwidget)
        self.btnTwo.setGeometry(QtCore.QRect(120, 350, 60, 60))
        self.btnTwo.setFont(font)
        self.btnTwo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTwo.setMouseTracking(False)
        self.btnTwo.setObjectName("btnTwo")
        self.btnSub = QtWidgets.QPushButton(self.centralwidget)
        self.btnSub.setGeometry(QtCore.QRect(260, 280, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSub.setFont(font)
        self.btnSub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSub.setMouseTracking(False)
        self.btnSub.setObjectName("btnSub")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(260, 349, 60, 131))
        self.btnAdd.setFont(font)
        self.btnAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAdd.setMouseTracking(False)
        self.btnAdd.setObjectName("btnAdd")
        self.btnDot = QtWidgets.QPushButton(self.centralwidget)
        self.btnDot.setGeometry(QtCore.QRect(190, 420, 60, 60))
        self.btnDot.setFont(font)
        self.btnDot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDot.setMouseTracking(False)
        self.btnDot.setObjectName("btnDot")
        self.btnZero = QtWidgets.QPushButton(self.centralwidget)
        self.btnZero.setGeometry(QtCore.QRect(50, 420, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnZero.setFont(font)
        self.btnZero.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnZero.setMouseTracking(False)
        self.btnZero.setObjectName("btnZero")
        self.btnDblZero = QtWidgets.QPushButton(self.centralwidget)
        self.btnDblZero.setGeometry(QtCore.QRect(120, 420, 60, 60))
        self.btnDblZero.setFont(font)
        self.btnDblZero.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDblZero.setMouseTracking(False)
        self.btnDblZero.setObjectName("btnDblZero")
        self.btnRBr = QtWidgets.QPushButton(self.centralwidget)
        self.btnRBr.setGeometry(QtCore.QRect(51, 490, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnRBr.setFont(font)
        self.btnRBr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRBr.setMouseTracking(False)
        self.btnRBr.setObjectName("btnRBr")
        self.btnLBr = QtWidgets.QPushButton(self.centralwidget)
        self.btnLBr.setGeometry(QtCore.QRect(121, 490, 60, 60))
        self.btnLBr.setFont(font)
        self.btnLBr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLBr.setMouseTracking(False)
        self.btnLBr.setObjectName("btnLBr")
        self.btnEq = QtWidgets.QPushButton(self.centralwidget)
        self.btnEq.setGeometry(QtCore.QRect(190, 490, 131, 60))
        self.btnEq.setFont(font)
        self.btnEq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEq.setMouseTracking(False)
        self.btnEq.setObjectName("btnEq")
        self.txtInput = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(50, 50, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtInput.setFont(font)
        self.txtInput.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.txtInput.setLineWrapColumnOrWidth(0)
        self.txtInput.setReadOnly(True)
        self.txtInput.setPlaceholderText("")
        self.txtInput.setObjectName("txtInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle("Calculator")
        MainWindow.setWindowIcon(QtGui.QIcon('icon.png'))
        self.btnC.setText(_translate("MainWindow", "C"))
        self.btnCE.setText(_translate("MainWindow", "CE"))
        self.btnAns.setText(_translate("MainWindow", "Ans"))
        self.btnNine.setText(_translate("MainWindow", "9"))
        self.btnSeven.setText(_translate("MainWindow", "7"))
        self.btnEight.setText(_translate("MainWindow", "8"))
        self.btnMul.setText(_translate("MainWindow", "*"))
        self.btnSix.setText(_translate("MainWindow", "6"))
        self.btnFour.setText(_translate("MainWindow", "4"))
        self.btnFive.setText(_translate("MainWindow", "5"))
        self.btnDiv.setText(_translate("MainWindow", "/"))
        self.btnThree.setText(_translate("MainWindow", "3"))
        self.btnOne.setText(_translate("MainWindow", "1"))
        self.btnTwo.setText(_translate("MainWindow", "2"))
        self.btnSub.setText(_translate("MainWindow", "-"))
        self.btnAdd.setText(_translate("MainWindow", "+"))
        self.btnDot.setText(_translate("MainWindow", "."))
        self.btnZero.setText(_translate("MainWindow", "0"))
        self.btnDblZero.setText(_translate("MainWindow", "00"))
        self.btnRBr.setText(_translate("MainWindow", "("))
        self.btnLBr.setText(_translate("MainWindow", ")"))
        self.btnEq.setText(_translate("MainWindow", "="))
